### ISSUE TITLE
Meta-tagging av spørsmål og svar

### ISSUE THREAD

**Issue by andnorda** [iterate/digital-leksehjelp#50]
- [x] Definere hvilke tagger som er interessante
- [ ] Lage tagger for spørsmålene som finnes
- [ ] Bruke de taggene til noe fornuftig

**Comment by andnorda** [comment]
Maries jobb
